[package]
name = "${Username}-${ProjectName}"
version = "${Version}"
edition = "2021"

[lib]
path = "${CMAKE_CURRENT_SOURCE_DIR}/src/Main.rs"
crate-type = ["cdylib"]

[dependencies]
windows = { version="0.46.0", features=["Win32_System_Com", "Win32_Foundation", "Win32_System_Ole"] }
clroxide = "1.1.1"
derivative = "2.2.0"
